### ISSUE TITLE
Pmmp4 

### ISSUE THREAD

**Issue by ByLex-69bits** [BoxOfDevs/CommandShop#19]
### Steps to reproduce

1. ...
2. ...
3. ...

### Server Information
* CommandShop Version: 
* Software Version: 
* Server OS: 

### CrashDumps/Errors
```
Paste your CrashDump or error by replacing this text (DON'T delete the backticks!)
```
Hey, there is a pmmp4 version ?

**Comment by AvgZing** [comment]
Lol no sorry
You can check the forks if you want, but BoxOfDevs really doesn't do much development for PMMP anymore. Feel free to join our discord https://discord.gg/adFhNCQ

**Comment by HimbeersaftLP** [comment]
@ByLex-69bits Which economy plugin are you using on 4.0.0? Or do you want to use this plugin with items only?

**Comment by Smorted** [comment]
@HimbeersaftLP economyapi, i also want to use this plugin

**Comment by HimbeersaftLP** [comment]
@Smorted As far as I know, EconomyAPI isn't supported anymore by anyone, is it?

**Comment by Smorted** [comment]
https://github.com/mathchat900/EconomyAPI-PM5

this is the one im currently using with no issues so far

tho im already using CommandShop in pm5 by removing item support since I don't really need it, feel free to wait for more demands or update now 👍

**Comment by HimbeersaftLP** [comment]
@Smorted Would you mind making your fork public so that I can add the item support back in for PM5?

**Comment by Smorted** [comment]
@HimbeersaftLP  sorry for the late response, it was not a fork since i downloaded it then edited it on my phone.

i uploaded it for u but keep in mind that this was only for private personal use so you will see some code commented out and the file "CShopListener" totally removed since i had no use of the code inside .

https://github.com/Smorted/CommandsShop
